### ISSUE TITLE
Error: File not found

### ISSUE THREAD

**Issue by jtheserg** [MrLinusMeow/bookbot#1]
I've tried running your program, but it failed. :(

Here's the error log:
<details><summary>Error log</summary>
<p>

```
PS P:\NOT-PORN> python main.py
Traceback (most recent call last):
  File "P:\NOT-PORN\main.py", line 62, in <module>
    main()
  File "P:\NOT-PORN\main.py", line 49, in main
    content = readContent(bookPath)
              ^^^^^^^^^^^^^^^^^^^^^
  File "P:\NOT-PORN\main.py", line 4, in readContent
    with open(input) as f:
         ^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'books/frankenstein.txt'
``` 

</p>
</details>

**Comment by MrLinusMeow** [comment]
Fixed in commit 59ded6f
